### ISSUE TITLE
Improve data structure

### ISSUE THREAD

**Issue by fukokami** [fukokami/github-page-profile#26]
# TODO

- [ ] Each array need field `id`
- [ ] Merge data to 1 `json` file
- [ ] Create structure data file template
