### ISSUE TITLE
Change ajax data name

### ISSUE THREAD

**Issue by fukokami** [fukokami/github-page-profile#41]
# TODO

## Rename file
- [x] src\js\ajax\get-profile-list.js → src\js\ajax\get-profile.js
- [x] src\js\ajax\get-project-list.js → src\js\ajax\get-project.js
- [x] src\js\ajax\get-storage-list.js → src\js\ajax\get-storage.js
- [x] src\js\ajax\get-user-info.js → src\js\ajax\get-user.js

## Change
export default  →  export
